version: '3'
services:
    server-php:
        container_name: server-php
        hostname: server-php
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - server-network
        depends_on:
            - server-postgres
            - server-redis

    server-nginx:
        image: nginx:1.23.1-alpine
        container_name: server-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - server-network
        depends_on:
            - server-php

    server-postgres:
        image: postgres:14.4-alpine
        container_name: server-postgres
        restart: unless-stopped
        ports:
            - "5434:5432"
        networks:
            - server-network
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: test
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        hostname: postgres

    test-server-postgres:
        image: postgres:14.4-alpine
        container_name: test-server-postgres
        restart: unless-stopped
        ports:
            - "5435:5432"
        networks:
            - server-network
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: test
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        hostname: postgres

    server-redis:
        image: redis:7.0.4-alpine3.16
        container_name: server-redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        tty: true
        networks:
            - server-network
        hostname: server-redis

    swagger-api-docs:
        build:
            context: .
            dockerfile: ./Dockerfile.swagger
        container_name: swagger-api-docs
        restart: unless-stopped
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - './swagger/:/usr/src/app/'
        ports:
            - "8081:3000"
networks:
    server-network:
        driver: bridge
